// AUTO-GENERATED BY scripts/generate-contract-models.mjs. DO NOT EDIT.

/**
 * @typedef {Object} AppleLoginRequest
 * @property {string|null} identityToken
 * @property {string|null} fullName
 * @property {string|null} email
 */

export const APPLE_LOGIN_REQUEST_FIELDS = Object.freeze([
  'identityToken',
  'fullName',
  'email',
]);

/**
 * @param {Partial<AppleLoginRequest>} [overrides={}]
 * @returns {AppleLoginRequest}
 */
export function createAppleLoginRequest(overrides = {}) {
  return {
    identityToken: null,
    fullName: null,
    email: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AuthErrorResponse
 * @property {string|null} code
 * @property {string|null} message
 * @property {boolean|null} captchaRequired
 * @property {number|null} remainingAttempts
 */

export const AUTH_ERROR_RESPONSE_FIELDS = Object.freeze([
  'code',
  'message',
  'captchaRequired',
  'remainingAttempts',
]);

/**
 * @param {Partial<AuthErrorResponse>} [overrides={}]
 * @returns {AuthErrorResponse}
 */
export function createAuthErrorResponse(overrides = {}) {
  return {
    code: null,
    message: null,
    captchaRequired: null,
    remainingAttempts: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AuthRequest
 * @property {string|null} username
 * @property {string|null} email
 * @property {string|null} password
 * @property {string|null} phone
 */

export const AUTH_REQUEST_FIELDS = Object.freeze([
  'username',
  'email',
  'password',
  'phone',
]);

/**
 * @param {Partial<AuthRequest>} [overrides={}]
 * @returns {AuthRequest}
 */
export function createAuthRequest(overrides = {}) {
  return {
    username: null,
    email: null,
    password: null,
    phone: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AuthResponse
 * @property {string|null} token
 * @property {string|null} type
 * @property {number|null} id
 * @property {string|null} username
 * @property {string|null} displayName
 * @property {string|null} email
 * @property {string|null} phone
 * @property {string|null} avatarUrl
 * @property {boolean|null} isGuest
 * @property {number|null} guestTrialRemaining
 */

export const AUTH_RESPONSE_FIELDS = Object.freeze([
  'token',
  'type',
  'id',
  'username',
  'displayName',
  'email',
  'phone',
  'avatarUrl',
  'isGuest',
  'guestTrialRemaining',
]);

/**
 * @param {Partial<AuthResponse>} [overrides={}]
 * @returns {AuthResponse}
 */
export function createAuthResponse(overrides = {}) {
  return {
    token: null,
    type: null,
    id: null,
    username: null,
    displayName: null,
    email: null,
    phone: null,
    avatarUrl: null,
    isGuest: null,
    guestTrialRemaining: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} CaptchaResponse
 * @property {string|null} captchaId
 * @property {string|null} imageBase64
 * @property {number|null} expiresInSeconds
 */

export const CAPTCHA_RESPONSE_FIELDS = Object.freeze([
  'captchaId',
  'imageBase64',
  'expiresInSeconds',
]);

/**
 * @param {Partial<CaptchaResponse>} [overrides={}]
 * @returns {CaptchaResponse}
 */
export function createCaptchaResponse(overrides = {}) {
  return {
    captchaId: null,
    imageBase64: null,
    expiresInSeconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ChangePasswordRequest
 * @property {string|null} currentPassword
 * @property {string|null} newPassword
 */

export const CHANGE_PASSWORD_REQUEST_FIELDS = Object.freeze([
  'currentPassword',
  'newPassword',
]);

/**
 * @param {Partial<ChangePasswordRequest>} [overrides={}]
 * @returns {ChangePasswordRequest}
 */
export function createChangePasswordRequest(overrides = {}) {
  return {
    currentPassword: null,
    newPassword: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ConfirmEmailChangeRequest
 * @property {string|null} newEmail
 * @property {string|null} code
 */

export const CONFIRM_EMAIL_CHANGE_REQUEST_FIELDS = Object.freeze([
  'newEmail',
  'code',
]);

/**
 * @param {Partial<ConfirmEmailChangeRequest>} [overrides={}]
 * @returns {ConfirmEmailChangeRequest}
 */
export function createConfirmEmailChangeRequest(overrides = {}) {
  return {
    newEmail: null,
    code: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ForgotPasswordRequest
 * @property {string|null} email
 */

export const FORGOT_PASSWORD_REQUEST_FIELDS = Object.freeze([
  'email',
]);

/**
 * @param {Partial<ForgotPasswordRequest>} [overrides={}]
 * @returns {ForgotPasswordRequest}
 */
export function createForgotPasswordRequest(overrides = {}) {
  return {
    email: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} LoginRequest
 * @property {string|null} username
 * @property {string|null} password
 * @property {string|null} captchaId
 * @property {string|null} captchaCode
 */

export const LOGIN_REQUEST_FIELDS = Object.freeze([
  'username',
  'password',
  'captchaId',
  'captchaCode',
]);

/**
 * @param {Partial<LoginRequest>} [overrides={}]
 * @returns {LoginRequest}
 */
export function createLoginRequest(overrides = {}) {
  return {
    username: null,
    password: null,
    captchaId: null,
    captchaCode: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ResetPasswordRequest
 * @property {string|null} email
 * @property {string|null} code
 * @property {string|null} newPassword
 */

export const RESET_PASSWORD_REQUEST_FIELDS = Object.freeze([
  'email',
  'code',
  'newPassword',
]);

/**
 * @param {Partial<ResetPasswordRequest>} [overrides={}]
 * @returns {ResetPasswordRequest}
 */
export function createResetPasswordRequest(overrides = {}) {
  return {
    email: null,
    code: null,
    newPassword: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SendEmailChangeCodeRequest
 * @property {string|null} newEmail
 */

export const SEND_EMAIL_CHANGE_CODE_REQUEST_FIELDS = Object.freeze([
  'newEmail',
]);

/**
 * @param {Partial<SendEmailChangeCodeRequest>} [overrides={}]
 * @returns {SendEmailChangeCodeRequest}
 */
export function createSendEmailChangeCodeRequest(overrides = {}) {
  return {
    newEmail: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SmsCodeRequest
 * @property {string|null} phone
 */

export const SMS_CODE_REQUEST_FIELDS = Object.freeze([
  'phone',
]);

/**
 * @param {Partial<SmsCodeRequest>} [overrides={}]
 * @returns {SmsCodeRequest}
 */
export function createSmsCodeRequest(overrides = {}) {
  return {
    phone: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SmsLoginRequest
 * @property {string|null} phone
 * @property {string|null} code
 */

export const SMS_LOGIN_REQUEST_FIELDS = Object.freeze([
  'phone',
  'code',
]);

/**
 * @param {Partial<SmsLoginRequest>} [overrides={}]
 * @returns {SmsLoginRequest}
 */
export function createSmsLoginRequest(overrides = {}) {
  return {
    phone: null,
    code: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} UserDTO
 * @property {number|null} id
 * @property {string|null} username
 * @property {string|null} displayName
 * @property {string|null} email
 * @property {string|null} phone
 * @property {string|null} avatarUrl
 * @property {string|null} bio
 * @property {string|null} gender
 * @property {string|null} birthday
 * @property {string|null} region
 * @property {string|null} appleUserId
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 */

export const USER_DTO_FIELDS = Object.freeze([
  'id',
  'username',
  'displayName',
  'email',
  'phone',
  'avatarUrl',
  'bio',
  'gender',
  'birthday',
  'region',
  'appleUserId',
  'createdAt',
  'updatedAt',
]);

/**
 * @param {Partial<UserDTO>} [overrides={}]
 * @returns {UserDTO}
 */
export function createUserDTO(overrides = {}) {
  return {
    id: null,
    username: null,
    displayName: null,
    email: null,
    phone: null,
    avatarUrl: null,
    bio: null,
    gender: null,
    birthday: null,
    region: null,
    appleUserId: null,
    createdAt: null,
    updatedAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} ActivitySummaryDTO
 * @property {number|null} water
 * @property {number|null} smoke
 * @property {number|null} poopCount
 * @property {number|null} poopSeconds
 */

export const ACTIVITY_SUMMARY_DTO_FIELDS = Object.freeze([
  'water',
  'smoke',
  'poopCount',
  'poopSeconds',
]);

/**
 * @param {Partial<ActivitySummaryDTO>} [overrides={}]
 * @returns {ActivitySummaryDTO}
 */
export function createActivitySummaryDTO(overrides = {}) {
  return {
    water: null,
    smoke: null,
    poopCount: null,
    poopSeconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} BadgeDTO
 * @property {string|null} key
 * @property {string|null} title
 * @property {string|null} description
 * @property {number|null} threshold
 * @property {number|null} current
 * @property {boolean|null} earned
 * @property {string|null} earnedAt
 */

export const BADGE_DTO_FIELDS = Object.freeze([
  'key',
  'title',
  'description',
  'threshold',
  'current',
  'earned',
  'earnedAt',
]);

/**
 * @param {Partial<BadgeDTO>} [overrides={}]
 * @returns {BadgeDTO}
 */
export function createBadgeDTO(overrides = {}) {
  return {
    key: null,
    title: null,
    description: null,
    threshold: null,
    current: null,
    earned: null,
    earnedAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RecordActivityRequest
 * @property {string|null} type
 * @property {number|null} durationSeconds
 */

export const RECORD_ACTIVITY_REQUEST_FIELDS = Object.freeze([
  'type',
  'durationSeconds',
]);

/**
 * @param {Partial<RecordActivityRequest>} [overrides={}]
 * @returns {RecordActivityRequest}
 */
export function createRecordActivityRequest(overrides = {}) {
  return {
    type: null,
    durationSeconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} AnalyticsEventBatchRequest
 * @property {Array<AnalyticsEventRequest>} events
 */

export const ANALYTICS_EVENT_BATCH_REQUEST_FIELDS = Object.freeze([
  'events',
]);

/**
 * @param {Partial<AnalyticsEventBatchRequest>} [overrides={}]
 * @returns {AnalyticsEventBatchRequest}
 */
export function createAnalyticsEventBatchRequest(overrides = {}) {
  return {
    events: [],
    ...overrides,
  };
}

/**
 * @typedef {Object} AnalyticsEventRequest
 * @property {string|null} eventName
 * @property {Record<string, unknown>} properties
 * @property {string|null} occurredAt
 */

export const ANALYTICS_EVENT_REQUEST_FIELDS = Object.freeze([
  'eventName',
  'properties',
  'occurredAt',
]);

/**
 * @param {Partial<AnalyticsEventRequest>} [overrides={}]
 * @returns {AnalyticsEventRequest}
 */
export function createAnalyticsEventRequest(overrides = {}) {
  return {
    eventName: null,
    properties: null,
    occurredAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} CheckinSummaryDTO
 * @property {boolean|null} checkedInToday
 * @property {number|null} currentStreak
 * @property {number|null} totalDays
 * @property {number|null} thisWeekDays
 */

export const CHECKIN_SUMMARY_DTO_FIELDS = Object.freeze([
  'checkedInToday',
  'currentStreak',
  'totalDays',
  'thisWeekDays',
]);

/**
 * @param {Partial<CheckinSummaryDTO>} [overrides={}]
 * @returns {CheckinSummaryDTO}
 */
export function createCheckinSummaryDTO(overrides = {}) {
  return {
    checkedInToday: null,
    currentStreak: null,
    totalDays: null,
    thisWeekDays: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} FishingReportRequest
 * @property {number|null} seconds
 */

export const FISHING_REPORT_REQUEST_FIELDS = Object.freeze([
  'seconds',
]);

/**
 * @param {Partial<FishingReportRequest>} [overrides={}]
 * @returns {FishingReportRequest}
 */
export function createFishingReportRequest(overrides = {}) {
  return {
    seconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} FishingSummaryDTO
 * @property {number|null} todaySeconds
 * @property {number|null} thisWeekSeconds
 * @property {number|null} totalSeconds
 */

export const FISHING_SUMMARY_DTO_FIELDS = Object.freeze([
  'todaySeconds',
  'thisWeekSeconds',
  'totalSeconds',
]);

/**
 * @param {Partial<FishingSummaryDTO>} [overrides={}]
 * @returns {FishingSummaryDTO}
 */
export function createFishingSummaryDTO(overrides = {}) {
  return {
    todaySeconds: null,
    thisWeekSeconds: null,
    totalSeconds: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} LeaderboardDTO
 * @property {Array<LeaderboardEntryDTO>} entries
 * @property {number|null} myScore
 */

export const LEADERBOARD_DTO_FIELDS = Object.freeze([
  'entries',
  'myScore',
]);

/**
 * @param {Partial<LeaderboardDTO>} [overrides={}]
 * @returns {LeaderboardDTO}
 */
export function createLeaderboardDTO(overrides = {}) {
  return {
    entries: [],
    myScore: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} LeaderboardEntryDTO
 * @property {number|null} rank
 * @property {string|null} nickname
 * @property {number|null} score
 * @property {boolean|null} me
 */

export const LEADERBOARD_ENTRY_DTO_FIELDS = Object.freeze([
  'rank',
  'nickname',
  'score',
  'me',
]);

/**
 * @param {Partial<LeaderboardEntryDTO>} [overrides={}]
 * @returns {LeaderboardEntryDTO}
 */
export function createLeaderboardEntryDTO(overrides = {}) {
  return {
    rank: null,
    nickname: null,
    score: null,
    me: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} FileUploadResponse
 * @property {string|null} fileName
 * @property {string|null} fileUrl
 * @property {string|null} fileType
 * @property {number|null} size
 */

export const FILE_UPLOAD_RESPONSE_FIELDS = Object.freeze([
  'fileName',
  'fileUrl',
  'fileType',
  'size',
]);

/**
 * @param {Partial<FileUploadResponse>} [overrides={}]
 * @returns {FileUploadResponse}
 */
export function createFileUploadResponse(overrides = {}) {
  return {
    fileName: null,
    fileUrl: null,
    fileType: null,
    size: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} SoupDTO
 * @property {string|null} text
 */

export const SOUP_DTO_FIELDS = Object.freeze([
  'text',
]);

/**
 * @param {Partial<SoupDTO>} [overrides={}]
 * @returns {SoupDTO}
 */
export function createSoupDTO(overrides = {}) {
  return {
    text: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RoleplayChatRequest
 * @property {string|null} persona
 * @property {string|null} customPersona
 * @property {Array<RoleplayMessage>} messages
 */

export const ROLEPLAY_CHAT_REQUEST_FIELDS = Object.freeze([
  'persona',
  'customPersona',
  'messages',
]);

/**
 * @param {Partial<RoleplayChatRequest>} [overrides={}]
 * @returns {RoleplayChatRequest}
 */
export function createRoleplayChatRequest(overrides = {}) {
  return {
    persona: null,
    customPersona: null,
    messages: [],
    ...overrides,
  };
}

/**
 * @typedef {Object} RoleplayMessage
 * @property {string|null} role
 * @property {string|null} content
 */

export const ROLEPLAY_MESSAGE_FIELDS = Object.freeze([
  'role',
  'content',
]);

/**
 * @param {Partial<RoleplayMessage>} [overrides={}]
 * @returns {RoleplayMessage}
 */
export function createRoleplayMessage(overrides = {}) {
  return {
    role: null,
    content: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RoleplayPersonaDTO
 * @property {string|null} code
 * @property {string|null} name
 * @property {string|null} emoji
 * @property {string|null} description
 */

export const ROLEPLAY_PERSONA_DTO_FIELDS = Object.freeze([
  'code',
  'name',
  'emoji',
  'description',
]);

/**
 * @param {Partial<RoleplayPersonaDTO>} [overrides={}]
 * @returns {RoleplayPersonaDTO}
 */
export function createRoleplayPersonaDTO(overrides = {}) {
  return {
    code: null,
    name: null,
    emoji: null,
    description: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} GenerateWeeklyRequest
 * @property {string|null} fragments
 */

export const GENERATE_WEEKLY_REQUEST_FIELDS = Object.freeze([
  'fragments',
]);

/**
 * @param {Partial<GenerateWeeklyRequest>} [overrides={}]
 * @returns {GenerateWeeklyRequest}
 */
export function createGenerateWeeklyRequest(overrides = {}) {
  return {
    fragments: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} WeeklyReportDTO
 * @property {number|null} id
 * @property {string|null} weekKey
 * @property {string|null} inputText
 * @property {string|null} content
 * @property {string|null} status
 * @property {string|null} createdAt
 */

export const WEEKLY_REPORT_DTO_FIELDS = Object.freeze([
  'id',
  'weekKey',
  'inputText',
  'content',
  'status',
  'createdAt',
]);

/**
 * @param {Partial<WeeklyReportDTO>} [overrides={}]
 * @returns {WeeklyReportDTO}
 */
export function createWeeklyReportDTO(overrides = {}) {
  return {
    id: null,
    weekKey: null,
    inputText: null,
    content: null,
    status: null,
    createdAt: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} UpsertWorkProfileRequest
 * @property {string|null} nickname
 * @property {string|null} city
 * @property {string|null} industry
 * @property {string|null} jobType
 * @property {string|null} gender
 * @property {string|null} workStart
 * @property {string|null} workEnd
 * @property {string|null} hatedRelation
 * @property {string|null} hatedNickname
 * @property {string|null} hatedTraits
 */

export const UPSERT_WORK_PROFILE_REQUEST_FIELDS = Object.freeze([
  'nickname',
  'city',
  'industry',
  'jobType',
  'gender',
  'workStart',
  'workEnd',
  'hatedRelation',
  'hatedNickname',
  'hatedTraits',
]);

/**
 * @param {Partial<UpsertWorkProfileRequest>} [overrides={}]
 * @returns {UpsertWorkProfileRequest}
 */
export function createUpsertWorkProfileRequest(overrides = {}) {
  return {
    nickname: null,
    city: null,
    industry: null,
    jobType: null,
    gender: null,
    workStart: null,
    workEnd: null,
    hatedRelation: null,
    hatedNickname: null,
    hatedTraits: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} WorkProfileDTO
 * @property {number|null} userId
 * @property {string|null} nickname
 * @property {string|null} city
 * @property {string|null} industry
 * @property {string|null} jobType
 * @property {string|null} gender
 * @property {string|null} workStart
 * @property {string|null} workEnd
 * @property {string|null} hatedRelation
 * @property {string|null} hatedNickname
 * @property {string|null} hatedTraits
 */

export const WORK_PROFILE_DTO_FIELDS = Object.freeze([
  'userId',
  'nickname',
  'city',
  'industry',
  'jobType',
  'gender',
  'workStart',
  'workEnd',
  'hatedRelation',
  'hatedNickname',
  'hatedTraits',
]);

/**
 * @param {Partial<WorkProfileDTO>} [overrides={}]
 * @returns {WorkProfileDTO}
 */
export function createWorkProfileDTO(overrides = {}) {
  return {
    userId: null,
    nickname: null,
    city: null,
    industry: null,
    jobType: null,
    gender: null,
    workStart: null,
    workEnd: null,
    hatedRelation: null,
    hatedNickname: null,
    hatedTraits: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} MessageResponse
 * @property {string|null} message
 * @property {string|null} service
 * @property {string|null} provider
 * @property {boolean|null} setupRequired
 */

export const MESSAGE_RESPONSE_FIELDS = Object.freeze([
  'message',
  'service',
  'provider',
  'setupRequired',
]);

/**
 * @param {Partial<MessageResponse>} [overrides={}]
 * @returns {MessageResponse}
 */
export function createMessageResponse(overrides = {}) {
  return {
    message: null,
    service: null,
    provider: null,
    setupRequired: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} PaginationMeta
 * @property {number|null} page
 * @property {number|null} size
 * @property {number|null} totalItems
 * @property {number|null} totalPages
 * @property {boolean|null} hasNext
 * @property {boolean|null} hasPrevious
 */

export const PAGINATION_META_FIELDS = Object.freeze([
  'page',
  'size',
  'totalItems',
  'totalPages',
  'hasNext',
  'hasPrevious',
]);

/**
 * @param {Partial<PaginationMeta>} [overrides={}]
 * @returns {PaginationMeta}
 */
export function createPaginationMeta(overrides = {}) {
  return {
    page: null,
    size: null,
    totalItems: null,
    totalPages: null,
    hasNext: null,
    hasPrevious: null,
    ...overrides,
  };
}

/**
 * @typedef {Object} RetrievalMeta
 * @property {string|null} scene
 * @property {string|null} keyword
 * @property {string|null} sortStrategy
 * @property {string|null} provider
 */

export const RETRIEVAL_META_FIELDS = Object.freeze([
  'scene',
  'keyword',
  'sortStrategy',
  'provider',
]);

/**
 * @param {Partial<RetrievalMeta>} [overrides={}]
 * @returns {RetrievalMeta}
 */
export function createRetrievalMeta(overrides = {}) {
  return {
    scene: null,
    keyword: null,
    sortStrategy: null,
    provider: null,
    ...overrides,
  };
}

export const CONTRACT_MODEL_NAMES = Object.freeze([
  'AppleLoginRequest',
  'AuthErrorResponse',
  'AuthRequest',
  'AuthResponse',
  'CaptchaResponse',
  'ChangePasswordRequest',
  'ConfirmEmailChangeRequest',
  'ForgotPasswordRequest',
  'LoginRequest',
  'ResetPasswordRequest',
  'SendEmailChangeCodeRequest',
  'SmsCodeRequest',
  'SmsLoginRequest',
  'UserDTO',
  'ActivitySummaryDTO',
  'BadgeDTO',
  'RecordActivityRequest',
  'AnalyticsEventBatchRequest',
  'AnalyticsEventRequest',
  'CheckinSummaryDTO',
  'FishingReportRequest',
  'FishingSummaryDTO',
  'LeaderboardDTO',
  'LeaderboardEntryDTO',
  'FileUploadResponse',
  'SoupDTO',
  'RoleplayChatRequest',
  'RoleplayMessage',
  'RoleplayPersonaDTO',
  'GenerateWeeklyRequest',
  'WeeklyReportDTO',
  'UpsertWorkProfileRequest',
  'WorkProfileDTO',
  'MessageResponse',
  'PaginationMeta',
  'RetrievalMeta',
]);

export const CONTRACT_MODEL_FACTORIES = Object.freeze({
  AppleLoginRequest: createAppleLoginRequest,
  AuthErrorResponse: createAuthErrorResponse,
  AuthRequest: createAuthRequest,
  AuthResponse: createAuthResponse,
  CaptchaResponse: createCaptchaResponse,
  ChangePasswordRequest: createChangePasswordRequest,
  ConfirmEmailChangeRequest: createConfirmEmailChangeRequest,
  ForgotPasswordRequest: createForgotPasswordRequest,
  LoginRequest: createLoginRequest,
  ResetPasswordRequest: createResetPasswordRequest,
  SendEmailChangeCodeRequest: createSendEmailChangeCodeRequest,
  SmsCodeRequest: createSmsCodeRequest,
  SmsLoginRequest: createSmsLoginRequest,
  UserDTO: createUserDTO,
  ActivitySummaryDTO: createActivitySummaryDTO,
  BadgeDTO: createBadgeDTO,
  RecordActivityRequest: createRecordActivityRequest,
  AnalyticsEventBatchRequest: createAnalyticsEventBatchRequest,
  AnalyticsEventRequest: createAnalyticsEventRequest,
  CheckinSummaryDTO: createCheckinSummaryDTO,
  FishingReportRequest: createFishingReportRequest,
  FishingSummaryDTO: createFishingSummaryDTO,
  LeaderboardDTO: createLeaderboardDTO,
  LeaderboardEntryDTO: createLeaderboardEntryDTO,
  FileUploadResponse: createFileUploadResponse,
  SoupDTO: createSoupDTO,
  RoleplayChatRequest: createRoleplayChatRequest,
  RoleplayMessage: createRoleplayMessage,
  RoleplayPersonaDTO: createRoleplayPersonaDTO,
  GenerateWeeklyRequest: createGenerateWeeklyRequest,
  WeeklyReportDTO: createWeeklyReportDTO,
  UpsertWorkProfileRequest: createUpsertWorkProfileRequest,
  WorkProfileDTO: createWorkProfileDTO,
  MessageResponse: createMessageResponse,
  PaginationMeta: createPaginationMeta,
  RetrievalMeta: createRetrievalMeta,
});

